#+TITLE: gdoc.el
#+AUTHOR: Houjun Liu

* Setup

*Begin by installing and setting up the [[https://github.com/prasmussen/gdrive][gdrive]] cli tool.*

Then, install this wonderful package.

#+begin_src elisp
(add-to-list 'load-path "/path/to/gdoc.el")
(require 'gdoc)
#+end_src

* Usage
Authenticate to =gdrive= by executing ~gdrive list~. Once logged in, execute ~M-x gdoc-edit~ to search and select a Google Doc to edit. Then, edit and save to the buffer that's opened normally.

* Caveats
There are many!
- This plugin only works with rich text (org), so *all structure (headings, tables, margins, etc.) will be gone* if you use it
- Quotes will likely look weird (i.e. same-y for begin and end quotes) unless you are the .00001% of the population that uses [[https://github.com/gareth-rees/smart-quotes][smart quotes-mode]] in Emacs. To solve, use that mode
- This package currently does very little:
  - It does not register a minor-mode as it just open an =.org= file in a special buffer with an on-save hook
  - It does not support text structuring, so things like headers would not really work
    
